name: Publish Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - run: corepack enable
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          package-manager-cache: false

      - name: Install dependencies
        run: pnpm install

      - name: Publish
        run: pnpm dlx pkg-pr-new publish --compact --pnpm --only-templates
